name: Actualizar Agenda Deportiva

on:
  schedule:
    # Ejecutar cada hora al minuto 30
    - cron: '30 * * * *'
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        # AÑADIMOS cloudscraper AQUÍ
        run: |
          pip install requests beautifulsoup4 cloudscraper

      - name: Ejecutar script de generación
        run: python .github/scripts/scraper.py

      - name: Commit y Push si hay cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

          if [ -f "ezdakit_eventos.m3u" ]; then
            git add ezdakit_eventos.m3u history/
            git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update agenda m3u [skip ci]" && git push)
          else
            echo "⚠️ ERROR: El archivo ezdakit_eventos.m3u no se ha generado."
            exit 1
          fi
