name: Update_dena

on:
  schedule:
    # Se ejecuta cada hora al minuto 35
    - cron: "45 * * * *"
  workflow_dispatch:
    inputs:
      testing_mode:
        description: 'Activar Modo Testing'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Dependencias
        run: pip install requests beautifulsoup4 cloudscraper

      - name: Ejecutar
        run: |
          if [ "${{ github.event.inputs.testing_mode }}" == "true" ]; then
            python .github/scripts/update_system.py --testing
          else
            python .github/scripts/update_system.py
          fi

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --staged --quiet || (git commit -m "Auto-Update $(date +'%Y-%m-%d %H:%M')" && git push)
